#
# This file is autogenerated by pip-compile with Python 3.11
# by the following command:
#
#    pip-compile
#
etcd3==0.12.0
    # via -r requirements.in
grpcio==1.67.0
    # via etcd3
protobuf==3.20.0
    # via etcd3
    # Required due to this error being generated when using anything newer
        # TypeError: Descriptors cannot be created directly.
        # If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
        # If you cannot immediately regenerate your protos, some other possible workarounds are:
        #  1. Downgrade the protobuf package to 3.20.x or lower.
        #  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower)
six==1.16.0
    # via etcd3
tenacity==9.0.0
    # via etcd3
